# Generated by Django 3.1.3 on 2021-10-29 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('supporting_doc', models.FileField(upload_to='candidate/experience/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashhired.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('proficiency', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashhired.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('technologies_used', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('supporting_media_or_link', models.CharField(max_length=5000)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashhired.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('supporting_doc', models.FileField(upload_to='candidate/skills')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashhired.candidate')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
