# Generated by Django 3.1.3 on 2021-10-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=25)),
                ('work_email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('auth_doc', models.FileField(upload_to='uploads/rec/docs/')),
                ('profile_pic', models.ImageField(upload_to='uploads/rec/pp/')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('fulltime', 'Full Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=25)),
                ('job_title', models.CharField(max_length=255)),
                ('functional_area', models.CharField(max_length=255)),
                ('jd', models.TextField()),
                ('required_skills', models.TextField()),
                ('required_experience', models.IntegerField()),
                ('required_education', models.TextField()),
                ('salary', models.IntegerField()),
                ('is_negotiable', models.BooleanField(default=False)),
                ('job_location', models.TextField()),
                ('upload_doc', models.FileField(upload_to='uploads/jp/docs/')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashhired.recruiter')),
            ],
        ),
    ]
