# Generated by Django 3.1.3 on 2021-10-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0002_auto_20211029_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=500)),
                ('instagram', models.URLField(blank=True, max_length=500)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('personal_website', models.URLField(blank=True, max_length=500)),
                ('codechef', models.URLField(blank=True, max_length=500)),
                ('hackerrank', models.URLField(blank=True, max_length=500)),
                ('kaggle', models.URLField(blank=True, max_length=500)),
                ('twitter', models.URLField(blank=True, max_length=500)),
                ('dribble', models.URLField(blank=True, max_length=500)),
                ('other', models.URLField(blank=True, max_length=500)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashhired.candidate')),
            ],
        ),
    ]
