# Generated by Django 3.1.3 on 2021-11-02 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0003_auto_20211029_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Resume',
            field=models.FileField(default=0, upload_to='candidate/resume/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='last_date_to_apply',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_cgpa',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=4),
        ),
    ]
