# Generated by Django 3.1.3 on 2021-11-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0004_auto_20211102_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishments',
            name='award_issued_by',
        ),
        migrations.RemoveField(
            model_name='accomplishments',
            name='award_name',
        ),
    ]
