# Generated by Django 3.1.3 on 2021-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0005_auto_20211118_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(blank=True, choices=[('native/bilingualproficiency', 'Native/Bilingual Proficiency'), ('fullprofessionalproficiency', 'Full Professional Proficiency'), ('elementaryproficiency', 'Elementary Proficiency'), ('professionalworkingproficiency', 'Professional Working Proficiency'), ('limitedworkingproficiency', 'Limited Working Proficiency')], max_length=100),
        ),
    ]
