# Generated by Django 3.1.3 on 2021-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0006_auto_20211125_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('fullprofessionalproficiency', 'Full Professional Proficiency'), ('limitedworkingproficiency', 'Limited Working Proficiency'), ('elementaryproficiency', 'Elementary Proficiency'), ('professionalworkingproficiency', 'Professional Working Proficiency'), ('native/bilingualproficiency', 'Native/Bilingual Proficiency')], max_length=100),
        ),
    ]
