# Generated by Django 3.1.3 on 2021-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0007_auto_20211125_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('native/bilingualproficiency', 'Native/Bilingual Proficiency'), ('professionalworkingproficiency', 'Professional Working Proficiency'), ('elementaryproficiency', 'Elementary Proficiency'), ('fullprofessionalproficiency', 'Full Professional Proficiency'), ('limitedworkingproficiency', 'Limited Working Proficiency')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='supporting_doc',
            field=models.FileField(null=True, upload_to='candidate/skills'),
        ),
    ]
