# Generated by Django 3.1.3 on 2021-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0008_auto_20211210_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(choices=[('limitedworkingproficiency', 'Limited Working Proficiency'), ('fullprofessionalproficiency', 'Full Professional Proficiency'), ('native/bilingualproficiency', 'Native/Bilingual Proficiency'), ('elementaryproficiency', 'Elementary Proficiency'), ('professionalworkingproficiency', 'Professional Working Proficiency')], max_length=100),
        ),
    ]
