# Generated by Django 3.1.3 on 2021-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0010_auto_20211210_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(choices=[('professionalworkingproficiency', 'Professional Working Proficiency'), ('native/bilingualproficiency', 'Native/Bilingual Proficiency'), ('elementaryproficiency', 'Elementary Proficiency'), ('fullprofessionalproficiency', 'Full Professional Proficiency'), ('limitedworkingproficiency', 'Limited Working Proficiency')], max_length=100),
        ),
    ]
