# Generated by Django 3.1.3 on 2021-12-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0013_auto_20211214_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(choices=[('elementaryproficiency', 'Elementary Proficiency'), ('native/bilingualproficiency', 'Native/Bilingual Proficiency'), ('professionalworkingproficiency', 'Professional Working Proficiency'), ('limitedworkingproficiency', 'Limited Working Proficiency'), ('fullprofessionalproficiency', 'Full Professional Proficiency')], max_length=100),
        ),
    ]
