# Generated by Django 3.1.3 on 2021-12-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashhired', '0014_auto_20211226_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(choices=[('professionalworkingproficiency', 'Professional Working Proficiency'), ('elementaryproficiency', 'Elementary Proficiency'), ('native/bilingualproficiency', 'Native/Bilingual Proficiency'), ('limitedworkingproficiency', 'Limited Working Proficiency'), ('fullprofessionalproficiency', 'Full Professional Proficiency')], max_length=100),
        ),
    ]
